#include <config.h>
set_state set_numkey_0 ={96, activate_function_key, deactivate_function_key};
set_state set_numkey_1 ={97, activate_auto_core, close_program};
set_state set_numkey_2 ={98, activate_word, activate_taskbar_10};
set_state set_numkey_3 ={99, activate_itunes, spotify_play_pause};
set_state set_numkey_4 ={100, print_daniel_choice, activate_chrome};
set_state set_numkey_5 ={101, print_lily_choice, activate_visual};
set_state set_numkey_6 ={102, print_luna_choice, activate_discord};
set_state set_numkey_7 ={103, print_gpt_message, activate_folder};
set_state set_numkey_8 ={104, print_spotify_songs, activate_firefox};
set_state set_numkey_9 ={105, print_timestamp, activate_taskbar_9};
set_state set_numkey_star ={106, get_user_sp_queue, print_episode_title};
set_state set_numkey_plus ={107, itunes_next_song, print_itunes_songs};
set_state set_numkey_enter ={108, print_choice_display, print_star_choice};
set_state set_numkey_dot ={109, spotify_next_song, activate_spotify};
set_state set_numkey_dash ={110, sp_switch_player, print_jose_choice};
set_state set_numkey_slash ={111, retrieve_and_delete_recycle_bin, print_eric_choice};